database:
  url: "jdbc:mysql://localhost:3306/database"
  username: "exampleuser"
  password: "examplepassword"

chat:
  # {player} -> Nick Gracza
  displayName: "{player}"
  delimiter: "&7»"
  # {message} -> wiadomość
  message: "{message}"

broadcast:
  format: "[&cBroadcast] &7»{message}"

msg:
  #
  # {sender} -> Osoba wysyłająca wiadomość
  # {reciever} -> Osoba otrzymująca wiadomość
  #
  format: "[{sender} &7-> &f{reciever}] » {message}"

helpOp:
  format: "&f[&cHelpOp&f] {sender} &7» {message}"

messages:
  playerNotOnline: "&cGracz nie jest online."