database:
  url: "jdbc:mysql://localhost:3306/database"
  username: "exampleuser"
  password: "examplepassword"

chat:
  # {player} -> Nick Gracza
  displayName: "{player}"
  delimiter: "&7»"
  # {message} -> wiadomość
  message: "{message}"

broadcast:
  format: "[&cBroadcast] &7»{message}"

msg:
  #
  # {sender} -> Osoba wysyłająca wiadomość
  # {reciever} -> Osoba otrzymująca wiadomość
  #
  format: "[{sender} &7-> &f{reciever}] » {message}"

helpOp:
  format: "&f[&cHelpOp&f] {sender} &7» {message}"

messages:
  playerNotOnline: "&cGracz nie jest online."
  groupNotSelected: "&e[Grupy]&f Nie wybrałeś grupy!"
  groupAlreadyExists: "&e[Grupy]&f Grupa już istnieje."
  groupCreated: "&e[Grupy]&f Utworzono grupę o nazwie {group}"
  notLeader: "&e[Grupy]&f Nie jesteś liderem grupy {group}!"
  alreadyInGroup: "&e[Grupy]&f Gracz {user} jest już w grupie!"
  alreadyInvited: "&e[Grupy]&f Gracz {user} jest już zaproszony do grupy!"
  successfullyInvited: "&e[Grupy]&f Zaproszono gracza {user}"
  invitePending: "&e[Grupy]&f  Zostałeś zaproszony do grupy {group}!"
  notInvited: "&e[Grupy]&f  Nie jesteś zaproszony do tej grupy!"
  inviteAccepted: "&e[Grupy]&f Zaakceptowano zaproszenie!"
  memberJoined: "&e[Grupy]&f Gracz {user} dołączył do grupy {group}!"
  switchToGlobal: "&e[Grupy]&f Ustawiono czat na globalny."
  groupSet: "&e[Grupy]&f Ustawiono czat na czat grupy {group}!"
  leaderCantLeaveGroup: "&e[Grupy]&f Nie możesz opuścić grupy {group}, gdyż jesteś jej liderem."
  groupDoesntExist: "&e[Grupy]&f Ta grupa nie istnieje."
  memberLeft: "&e[Grupy]&f {user} opuścił grupę {group}"
  groupLeft: "&e[Grupy]&f Opuściłeś grupę {group}"
  notInGroup: "&e[Grupy]&f Gracz {user} nie należy do tej grupy."
  successfullyKicked: "&e[Grupy]&f Wyrzucono gracza {user}"
  gotKicked: "&e[Grupy]&f Wyrzucono cię z grupy {group}"
  memberGotKicked: "&e[Grupy]&f Gracz {user} został wyrzucony z grupy {group}"