name: depixel
version: '${project.version}'
main: pl.nivse.depixel.Depixel
api-version: 1.20
default-permission: op
permissions:
  depixel.color:
    description: Pozwala używać kolory (MiniMessage)
  depixel.bold:
    description: Pozwala używać pogrubienia (MiniMessage)
  depixel.italic:
    description: Pozwala używać pochylenia (MiniMessage)
  depixel.underlined:
    description: Pozwala używać podkreślenia (MiniMessage)
  depixel.strikethrough:
    description: Pozwala używać przekreślenia (MiniMessage)
  depixel.obfuscated:
    description: Pozwala na zakrycie wiadomości (MiniMessage)
  depixel.gradient:
    description: Pozwala używać gradientu (MiniMessage)
  depixel.rainbow:
    description: Pozwala używać tęczy (MiniMessage)
  depixel.hover:
    description: Pozwala na dodawanie do wiadomości tooltipa po najechaniu na nią (MiniMessage)
  depixel.click:
    description: Pozwala na dodawanie do wiadomości "przycisków"(?) (MiniMessage)
  depixel.legacy:
    description: Pozwala na używanie legacy formatowania w wiadomościach, np "&e&lSiema!"
  depixel.helpOp:
    description: Pozwala na widzenie wiadomości na HelpOP
  depixel.broadcast:
    description: Pozwala używać komendy broadcast
  depixel.reload:
    description: Pozwala używać komendy reload